services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - cmd/auction/.env
    volumes:
      - .docker/mongo-data:/data/db
    networks:
      - localNetwork

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    networks:
      - localNetwork
    depends_on:
      - mongodb

networks:
  localNetwork:
    driver: bridge