@auctionId=0a7d3fe6-6f5e-4af8-9a1c-f7bf70ca0463
@userId=9db32183-9d9a-453a-b89f-cbf84af2634e

### GET /users

GET http://localhost:8080/users HTTP/2
Host: localhost:8080
Content-Type: application/json

### GET /users/:userId

GET http://localhost:8080/users/{{userId}} HTTP/2
Host: localhost:8080
Content-Type: application/json

### POST /users

POST http://localhost:8080/users HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "name": "John Doe"
}

### GET /auctions

GET http://localhost:8080/auctions?status=0 HTTP/2
Host: localhost:8080
Content-Type: application/json

### GET /auctions/:auctionId

GET http://localhost:8080/auctions/{{auctionId}} HTTP/2
Host: localhost:8080
Content-Type: application/json

### POST /auctions

POST http://localhost:8080/auctions HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "product_name": "iPhone",
  "category": "Electronic",
  "description": "iPhone 16 Pro Max",
  "condition": 0
}

### GET /auctions/:auctionId/winner

GET http://localhost:8080/auctions/{{auctionId}}/winner HTTP/2
Host: localhost:8080
Content-Type: application/json

### POST /bids

POST http://localhost:8080/bids HTTP/2
Host: localhost:8080
Content-Type: application/json

{
  "user_id": "{{userId}}",
  "auction_id": "{{auctionId}}",
  "amount": 1.0
}

### GET /auctions/:auctionId/bids

GET http://localhost:8080/bids/{{auctionId}} HTTP/2
Host: localhost:8080
Content-Type: application/json
